import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "DevFlow App",
  description: "Generated by Mohsen Parsa",

  // favicon
  icons: {
    icon: "/images/favicon.svg",
  },

  openGraph: {
    title: "DevFlow App",
    description: "Generated by Mohsen Parsa",
    url: "https://dev-flow-dashboard.vercel.app/",
    siteName: "DevFlow App",
    images: [
      {
        url: "/images/site-logo.svg",
        width: 800,
        height: 600,
      },
    ],
    locale: "en-US",
    type: "website",
  },

  // Twitter Card
  twitter: {
    card: "summary_large_image",
    title: "DevFlow App",
    description: "Generated by Mohsen Parsa",
    images: ["/og-image.png"],
    site: "@yourTwitterHandle", // optional
    creator: "@yourTwitterHandle",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
