import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/context/ThemeProvider";
import { Toaster } from "sonner";
import { SessionProvider } from "next-auth/react";
import { auth } from "../../auth";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "DevFlow App",
  description: "Generated by Mohsen Parsa",

  // favicon
  icons: {
    icon: "/images/favicon.svg",
  },

  openGraph: {
    title: "DevFlow App",
    description: "Generated by Mohsen Parsa",
    url: "https://dev-flow-dashboard.vercel.app/",
    siteName: "DevFlow App",
    images: [
      {
        url: "/images/site-logo.svg",
        width: 800,
        height: 600,
      },
    ],
    locale: "en-US",
    type: "website",
  },

  // Twitter Card
  twitter: {
    card: "summary_large_image",
    title: "DevFlow App",
    description: "Generated by Mohsen Parsa",
    images: ["/og-image.png"],
    site: "@yourTwitterHandle", // optional
    creator: "@yourTwitterHandle",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html suppressHydrationWarning lang="en">
      <SessionProvider session={session}>
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <Toaster
              richColors
              toastOptions={{
                classNames: {
                  success: "bg-white text-green-500",
                  error: "bg-white text-red-500",
                },
              }}
            />
          </ThemeProvider>
        </body>
      </SessionProvider>
    </html>
  );
}
